In [1]:
import pandas as pd

In [4]:
pd.read_json('r-train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [5]:
# pd.read_json('#url')

# Working with SQL

In [27]:
import psycopg2

conn_obj =  psycopg2.connect(
    host="localhost",
    database="postgres",
    user="postgres",
    password="postgres")

pd.read_sql_query("Select * from title", conn_obj)

OperationalError: FATAL:  password authentication failed for user "postgres"


## API: Application Programming Interface

In [7]:
import requests

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzNDRmYmIzMTkzNjI5MjA3MmE0YjMxNWE5ODU3MzdmZCIsInN1YiI6IjY1ODRiMTk1OTljOTY0NjA1MGVmNjgzMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.ohabRaa9tZ82x1To1UVOZ8ROa0NWL8jmtC6yIuLZZXw"
}

{"page":1,"results":[{"adult":false,"backdrop_path":"/bmlkLCjrIWnnZzdAQ4uNPG9JFdj.jpg","genre_ids":[35,10751,14],"id":787699,"original_language":"en","original_title":"Wonka","overview":"Willy Wonka – chock-full of ideas and determined to change the world one delectable bite at a time – is proof that the best things in life begin with a dream, and if you’re lucky enough to meet Willy Wonka, anything is possible.","popularity":1081.396,"poster_path":"/qhb1qOilapbapxWQn9jtRCMwXJF.jpg","release_date":"2023-12-06","title":"Wonka","video":false,"vote_average":7.3,"vote_count":386},{"adult":false,"backdrop_path":"/jXJxMcVoEuXzym3vFnjqDW4ifo6.jpg","genre_ids":[28,12,14],"id":572802,"original_language":"en","original_title":"Aquaman and the Lost Kingdom","overview":"Black Manta, still driven by the need to avenge his father's death and wielding the power of the mythic Black Trident, will stop at nothing to take Aquaman down once and for all. To defeat him, Aquaman must turn to his imprisoned brother Orm, the former King of Atlantis, to forge an unlikely alliance in order to save the world from irreversible destruction.","popularity":964.868,"poster_path":"/8xV47NDrjdZDpkVcCFqkdHa3T0C.jpg","release_date":"2023-12-20","title":"Aquaman and the Lost Kingdom","video":false,"vote_average":7.7,"vote_count":33},{"adult":false,"backdrop_path":"/1X7vow16X7CnCoexXh4H4F2yDJv.jpg","genre_ids":[80,18,36],"id":466420,"original_language":"en","original_title":"Killers of the Flower Moon","overview":"When oil is discovered in 1920s Oklahoma under Osage Nation land, the Osage people are murdered one by one—until the FBI steps in to unravel the mystery.","popularity":879.598,"poster_path":"/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg","release_date":"2023-10-18","title":"Killers of the Flower Moon","video":false,"vote_average":7.6,"vote_count":1511},{"adult":false,"backdrop_path":"/8GnWDLn2AhnmkQ7hlQ9NJUYobSS.jpg","genre_ids":[18,878,28],"id":695721,"original_language":"en","original_title":"The Hunger Games: The Ballad of Songbirds & Snakes","overview":"64 years before he becomes the tyrannical president of Panem, Coriolanus Snow sees a chance for a change in fortunes when he mentors Lucy Gray Baird, the female tribute from District 12.","popularity":810.099,"poster_path":"/mBaXZ95R2OxueZhvQbcEWy2DqyO.jpg","release_date":"2023-11-15","title":"The Hunger Games: The Ballad of Songbirds & Snakes","video":false,"vote_average":7.2,"vote_count":810},{"adult":false,"backdrop_path":"/k1KrbaCMACQiq7EA0Yhw3bdzMv7.jpg","genre_ids":[16,10751,10402,14,35],"id":901362,"original_language":"en","original_title":"Trolls Band Together","overview":"When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.","popularity":782.173,"poster_path":"/bkpPTZUdq31UGDovmszsg2CchiI.jpg","release_date":"2023-10-12","title":"Trolls Band Together","video":false,"vote_average":7.2,"vote_count":389},{"adult":false,"backdrop_path":"/9jPoyxjiEYPylUIMI3Ntixf8z3M.jpg","genre_ids":[16,12,35,10751],"id":520758,"original_language":"en","original_title":"Chicken Run: Dawn of the Nugget","overview":"A band of fearless chickens flock together to save poultry-kind from an unsettling new threat: a nearby farm that's cooking up something suspicious.","popularity":751.068,"poster_path":"/exNtEY8QUuQh9e23wSQjkPxKIU3.jpg","release_date":"2023-12-08","title":"Chicken Run: Dawn of the Nugget","video":false,"vote_average":7.6,"vote_count":156},{"adult":false,"backdrop_path":"/zIYROrkHJPYB3VTiW1L9QVgaQO.jpg","genre_ids":[28,35],"id":897087,"original_language":"en","original_title":"Freelance","overview":"An ex-special forces operative takes a job to provide security for a journalist as she interviews a dictator, but a military coup breaks out in the middle of the interview, they are forced to escape into the jungle where they must survive.","popularity":730.353,"poster_path":"/7Bd4EUOqQDKZXA6Od5gkfzRNb0.jpg","release_date":"2023-01-05","title":"Freelance","video":false,"vote_average":6.4,"vote_count":337},{"adult":false,"backdrop_path":"/tLsc8SCFO0rMVgVyNm9XtfnyX84.jpg","genre_ids":[18,9648,53,878],"id":726209,"original_language":"en","original_title":"Leave the World Behind","overview":"A family's getaway to a luxurious rental home takes an ominous turn when a cyberattack knocks out their devices—and two strangers appear at their door.","popularity":695.078,"poster_path":"/29rhl1xopxA7JlGVVsf1UHfYPvN.jpg","release_date":"2023-11-22","title":"Leave the World Behind","video":false,"vote_average":6.6,"vote_count":944},{"adult":false,"backdrop_path":"/15Fe18IglCCP1jJoj5F529on0IA.jpg","genre_ids":[28,35],"id":1029575,"original_language":"en","original_title":"The Family Plan","overview":"Dan Morgan is many things: a devoted husband, a loving father, a celebrated car salesman. He's also a former assassin. And when his past catches up to his present, he's forced to take his unsuspecting family on a road trip unlike any other.","popularity":630.244,"poster_path":"/jLLtx3nTRSLGPAKl4RoIv1FbEBr.jpg","release_date":"2023-12-14","title":"The Family Plan","video":false,"vote_average":7.6,"vote_count":232},{"adult":false,"backdrop_path":"/9PqD3wSIjntyJDBzMNuxuKHwpUD.jpg","genre_ids":[16,35,10751],"id":1075794,"original_language":"en","original_title":"Leo","overview":"Jaded 74-year-old lizard Leo has been stuck in the same Florida classroom for decades with his terrarium-mate turtle. When he learns he only has one year left to live, he plans to escape to experience life on the outside but instead gets caught up in the problems of his anxious students — including an impossibly mean substitute teacher.","popularity":617.925,"poster_path":"/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg","release_date":"2023-11-17","title":"Leo","video":false,"vote_average":7.6,"vote_count":609},{"adult":false,"backdrop_path":"/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg","genre_ids":[18,36],"id":872585,"original_language":"en","original_title":"Oppenheimer","overview":"The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.","popularity":582.685,"poster_path":"/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg","release_date":"2023-07-19","title":"Oppenheimer","video":false,"vote_average":8.1,"vote_count":5503},{"adult":false,"backdrop_path":"/t5zCBSB5xMDKcDqe91qahCOUYVV.jpg","genre_ids":[27,9648],"id":507089,"original_language":"en","original_title":"Five Nights at Freddy's","overview":"Recently fired and desperate for work, a troubled young man named Mike agrees to take a position as a night security guard at an abandoned theme restaurant: Freddy Fazbear's Pizzeria. But he soon discovers that nothing at Freddy's is what it seems.","popularity":524.657,"poster_path":"/7BpNtNfxuocYEVREzVMO75hso1l.jpg","release_date":"2023-10-25","title":"Five Nights at Freddy's","video":false,"vote_average":7.8,"vote_count":2893},{"adult":false,"backdrop_path":"/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg","genre_ids":[28,12,18],"id":670292,"original_language":"en","original_title":"The Creator","overview":"Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.","popularity":519.127,"poster_path":"/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg","release_date":"2023-09-27","title":"The Creator","video":false,"vote_average":7.1,"vote_count":1503},{"adult":false,"backdrop_path":"/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg","genre_ids":[28,80,53],"id":385687,"original_language":"en","original_title":"Fast X","overview":"Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.","popularity":508.326,"poster_path":"/fiVW06jE7z9YnO4trhaMEdclSiC.jpg","release_date":"2023-05-17","title":"Fast X","video":false,"vote_average":7.2,"vote_count":4497},{"adult":false,"backdrop_path":"/gvNmnvu13TPAewP54hvCyuHwNwR.jpg","genre_ids":[28,27,878],"id":920081,"original_language":"en","original_title":"Megaboa","overview":"On a trip to Colombia, a group of college students encounter a fifty-foot boa constrictor, hungry for blood.","popularity":494.068,"poster_path":"/sAnAMv3eyQiGI1z2k8NsvH0Y6r5.jpg","release_date":"2021-11-26","title":"Megaboa","video":false,"vote_average":6.5,"vote_count":438},{"adult":false,"backdrop_path":"/3d39m2S3WynknLVGpsOxhiSKbgQ.jpg","genre_ids":[53,28],"id":1146225,"original_language":"en","original_title":"Escaping Paradise","overview":"When a young couple vacations on an exotic island, they encounter a dangerous fugitive who is determined to keep them from leaving.","popularity":461.494,"poster_path":"/3UCTls0hVKMCwWtkTmwKcCOzlgu.jpg","release_date":"2023-07-08","title":"Escaping Paradise","video":false,"vote_average":4.7,"vote_count":3},{"adult":false,"backdrop_path":"/rMvPXy8PUjj1o8o1pzgQbdNCsvj.jpg","genre_ids":[28,12,53],"id":299054,"original_language":"en","original_title":"Expend4bles","overview":"Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.","popularity":428.282,"poster_path":"/iwsMu0ehRPbtaSxqiaUDQB9qMWT.jpg","release_date":"2023-09-15","title":"Expend4bles","video":false,"vote_average":6.4,"vote_count":904},{"adult":false,"backdrop_path":"/AucuqDaUW4z1oT5XyL71qwRY2F6.jpg","genre_ids":[27,53],"id":983507,"original_language":"no","original_title":"Meg, deg & Frank","overview":"Christian - a millionaire heir, meets Sigrid - a young student, on a dating app. They hit it off quickly, but there's only one problem: Christian lives with Frank, a man who dresses up and constantly acts like a dog.","popularity":420.453,"poster_path":"/9DPG1gxLwV2oyFdHq3SnISsWbse.jpg","release_date":"2022-06-03","title":"Good Boy","video":false,"vote_average":6.8,"vote_count":111},{"adult":false,"backdrop_path":"/tB59fpPnQITgnfxPfMf2gxASTeC.jpg","genre_ids":[28,53,18],"id":656156,"original_language":"ko","original_title":"보호자","overview":"After 10 years of incarceration on behalf of his employer, all Su-hyuk wants is a normal life - one he hopes will include his former girlfriend, Min-seo, and their daughter, In-bi. But once you've penetrated the upper echelons of the underworld, normal can prove hard to come by. Sometime in the past decade, meanwhile, Su-hyuk's employer has adopted an air of legitimacy. These days, the old gang steal and murder in the name of urban development. And they want the reluctant Su-hyuk on board.","popularity":404.916,"poster_path":"/ePwZs1oOh4pg8UZP8DuVZZeIn89.jpg","release_date":"2023-08-15","title":"A Man of Reason","video":false,"vote_average":6.5,"vote_count":31},{"adult":false,"backdrop_path":"/nHf61UzkfFno5X1ofIhugCPus2R.jpg","genre_ids":[35,12,14],"id":346698,"original_language":"en","original_title":"Barbie","overview":"Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.","popularity":397.538,"poster_path":"/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg","release_date":"2023-07-19","title":"Barbie","video":false,"vote_average":7.2,"vote_count":6371}],"total_pages":41586,"total_results":831717}

In [23]:
df = pd.DataFrame()
for i in range(1, 100):
    url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=" + str(i)
    response = requests.get(url, headers=headers)
    temp_df = pd.DataFrame(response.json()['results'])[['id', 'title', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
    df = pd.concat([df, temp_df], axis=0, ignore_index=True)

In [22]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,140.304,8.708,19157
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,112.653,8.707,25136
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,75.214,8.588,11548
3,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-12-15,79.217,8.573,14898
4,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,32.137,8.547,4302
...,...,...,...,...,...,...,...
9012,12142,Alone in the Dark,Edward Carnby is a private investigator specia...,2005-01-28,27.367,3.228,554
9013,5491,Battlefield Earth,"In the year 3000, man is no match for the Psyc...",2000-05-12,37.857,3.222,769
9014,11059,House of the Dead,"Set on an island off the coast, a techno rave ...",2003-04-11,14.479,3.141,361
9015,14164,Dragonball Evolution,"On his 18th birthday, Goku receives a mystical...",2009-03-12,25.306,2.887,1930
9016,40016,Birdemic: Shock and Terror,A platoon of eagles and vultures attacks the r...,2010-02-27,13.238,2.100,306